Apply damage to original attack target
vttred/ose pull request #368
Opened 2023-03-18 12:54 UTC by amir-arad

Add the possibility to inflict damage from an attack to the original target of the attack. The original target is determined at the time of the attack, so even if the atytacking player changed target the damage will go to the right actor. 

Protected by `applyDamageOption` (preexisting) feature flag

fixes #287 

![image](https://user-images.githubusercontent.com/6019373/226107102-a512325f-d573-4381-95d9-6a7cff1e1106.png)

2023-03-20 14:06 UTC, wyrmisis requested changes
I haven't been able to test the changes, but everything here looks reasonable to me. I left some general code quality questions.

2023-03-20 15:23 UTC, amir-arad commented on src/module/chat.ts
> +      case "originalTarget":
I can't find a reference for a settings value being derived from `CONFIG.OSE`, a pointer will be welcomed.

IMO The constants here are not magical, they are enum strings. also Typescript matches them against the relevant possible values of `dmgTgt` determined in the settings, where each value has a  defined meaning. changing one of the strings should break TS type check.

2023-03-20 15:33 UTC, amir-arad commented on src/module/chat.ts
> +  if (dmgTgt === `originalTarget`) {
done

2023-03-20 15:42 UTC, wyrmisis commented on src/module/chat.ts
> +      case "originalTarget":
It's not an exact example, but we're referencing props of `CONFIG.OSE` in the character data model when setting up encumbrance: https://github.com/vttred/ose/blob/main/src/module/actor/data-model-character.js#L21

While Typescript might validate those strings at compile time, I do think that having a single place where these strings are defined, that we then reference when we use them, is a good thing to do. Heck, we can even stick with enums; just export them from somewhere, and refer to them here and in our settings.

2023-03-20 16:32 UTC, amir-arad commented on src/module/chat.ts
> +      case "originalTarget":
done

2023-03-21 21:42 UTC, wyrmisis commented on src/module/chat.ts
> +      console.log('unknown setting');
I think we should make this more specific, and a UI warning. We *shouldn't* end up here, but if we do, it'd be helpful if a user could tell us how they got here!

2023-03-21 21:43 UTC, wyrmisis commented on src/module/chat.ts
@bakbakbakbakbak Just a heads up, I forget if you had tests written for this file or the other stuff in this PR, but this might change things for you.

2023-03-21 21:44 UTC, wyrmisis reviewed
I'm good with the changes here, but I'd appreciate if someone else could have a look!

2023-03-22 04:59 UTC, bakbakbakbakbak commented on src/module/chat.ts
Thanks for the notice, I'll take a look at this

2023-03-27 13:58 UTC, anthonyronda commented on src/module/chat.ts
probably best to revisit in a later revision of 0.8.x and leave the test as-is until after merging. We're probably expecting a non-zero amount of other surprises after such a large merge

2023-03-27 17:47 UTC, bakbakbakbakbak commented on src/module/chat.ts
Yeah, I am having quite a bit on my plate right now either, and I have noticed that I procrastinate on this check here.

2023-03-28 17:17 UTC, anthonyronda requested changes
The PR didn't seem to work as intended (got the new UI error message with each attack attempt) and in debugging I discovered a cause, shown below

2023-03-28 17:17 UTC, anthonyronda commented on src/templates/chat/roll-attack.html
> +            vs {{result.victim.name}}
I like this :)

2023-03-28 18:24 UTC, amir-arad commented on src/module/config.ts
> +  },
done

2023-03-28 18:39 UTC, anthonyronda approved these changes
Confirmed working in Foundry

LGTM

2023-03-28 18:39 UTC, anthonyronda commented on src/module/chat.ts
> +        configName: 'applyDamageOption',
Oh nice, good idea :D

2023-03-28 18:39 UTC, merged

2023-03-28 18:40 UTC, anthonyronda commented
Thanks for your contribution @amir-arad 🎉 

@all-contributors please add @amir-arad for code

2023-03-28 18:42 UTC, anthonyronda commented
@amir-arad please also take a look at #59 and tell me your preferred name and optional email for entering in the AUTHORS file :)