Party Sheet button fix
vttred/ose pull request #551
Opened 2024-12-19 13:46 UTC by JustinFreitas

Puts the button on the search line before the search icon.  Adjust as necessary.

2024-12-19 19:43 UTC, wyrmisis commented
Mind dropping a screenshot for this change?

2024-12-20 00:07 UTC, JustinFreitas commented
> Mind dropping a screenshot for this change?

![image](https://github.com/user-attachments/assets/1ca73ab2-4060-4425-9998-c2cb5224ee18)

2024-12-24 13:05 UTC, Rughalt requested changes
Onbe minor change I would like to request - the button seems to miss left margin and it looks off when taking into account the buttons above it.

2024-12-24 13:26 UTC, JustinFreitas commented
> Onbe minor change I would like to request - the button seems to miss left margin and it looks off when taking into account the buttons above it.

Yeah, I can get that figured out.  Was the Party Sheet button on the upper button line before or was it always on the line with the search controls?  Anyway, if you remember, let me know... for now, I'll continue with it on the search line.

2024-12-24 13:45 UTC, Rughalt commented
Search line is good, lets just make it nice and tidy CSS wise! Thanks!

2024-12-24 16:43 UTC, JustinFreitas commented on src/scss/apps.scss
> +    margin: 4px;
Adding in this margin it now looks like this.

![image](https://github.com/user-attachments/assets/da442bc7-dc54-4836-8c94-cd8097342179)

2024-12-24 18:09 UTC, Rughalt approved these changes

2024-12-24 18:09 UTC, merged